# Generated by Django 5.1.7 on 2025-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('topic', models.CharField(max_length=100)),
                ('consultant', models.CharField(max_length=100)),
            ],
        ),
    ]
