# Generated by Django 5.1.7 on 2025-03-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='consultant',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='topic',
        ),
    ]
