# Generated by Django 5.1.7 on 2025-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_consultant_booking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultant',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='topic',
            field=models.CharField(default='General Consultation', max_length=200),
        ),
    ]
